// Code generated by goctl. DO NOT EDIT.
package types

type Order struct {
	Table int    `json:"table"`
	Items []Item `json:"items"`
}

type AddToOrder struct {
	Id string `path:"id"`
	Items []Item `json:"items"`
}

type CreatedOrder struct {
	Id           string  `json:"id"`
	CreatedDate  string  `json:"created_date"`
	Table        int     `json:"table"`
	Items        []Item  `json:"item"`
	Paid         bool    `json:"paid"`
	Status       string  `json:"status"`
	SummaryPrice float64 `json:"summary_price"`
}

type Item struct {
	Name       string  `json:"name"`
	Count      int     `json:"count"`
	PiecePrice float64 `json:"price_per_piece"`
	IsDilivered bool `json:"delivered"` 
}

type Table struct {
	Number int
	Token string
}

type TableNumber struct {
	Number int `path:"table"`
}