// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"qr-ordering-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Middleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: createOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:table/update",
					Handler: updateOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:table/add",
					Handler: addOrderHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/ordering/orders"),
	)
}
